### ISSUE TITLE
show function not working

### ISSUE THREAD

**Issue by ipa-jxk** [erium/Halerium#5]
## Expected Behavior
Show function sends graph to gui for visualization in new browser tab.

## Current Behavior
After calling the show function and clicking on 'Open Graph '...' in new tab ' a new tab opens but only the message 'Page not found' appears.

## Steps to Reproduce
Create a graph g, call the function show(g) and click on 'Open Graph 'g' in new tab'.

## Environment
 - Windows 10
 - Chrome 95.0.4638.69 and Firefox 91.3.0
 - Does the issue persist with all addons disabled (e.g. in incognito mode)? Yes

**Comment by MakGre** [comment]
Dear ipa-jxk,
thank you for making us aware of the bug.
We can reproduce the bug on our end and are working on it. We will return to you with more details asap.

**Comment by MakGre** [comment]
Dear ipa-jxk,
we deployed a hotfix yesterday. It works in all of our tests.
Can you confirm that it works as expected for you?

**Comment by ipa-jxk** [comment]
Yes, it works. Thank you!
